#############
# @url2=http://localhost:1337
# @url2=https://messagetest.caprover.credot-web.com
@url2=https://message.production.credot-web.com
#############
GET {{url2}}/api/services

#############
POST {{url2}}/api/services
Content-Type: application/json

{
    "data":{
        "name":"test",
        "secret":"123456"
    }
}

#############
DELETE {{url2}}/api/services/2

#############
POST {{url2}}/api/messages
Content-Type: application/json

{
    "data":{
        "phone":"0921771865",
        "content":"test message",
        "service":"peman",
        "timestamp":"1641204444",
        "checksum":"6b67e6407ae3ed5df1b351b81aca7bfcdde16162fece7f68f8ea77e2ef575086"
    }
}

#############
GET {{url2}}/api/messages
Content-Type: application/json
#############
GET {{url2}}/api/messages?filters[service][$eq]=peman&checksum=299439a4482e126ba55303805b133367b6a9a2d910af18c7a81200b7df73adcc&timestamp=1641204143&pagination[page]=1&pagination[pageSize]=5&filters[createdAt][$gt]=2021-12-30T08:14:29.565Z
Content-Type: application/json