#############
@url2=http://localhost:1337

#############
GET {{url2}}/api/services

#############
POST {{url2}}/api/services
Content-Type: application/json

{
    "data":{
        "name":"test",
        "secret":"123456"
    }
}

#############
DELETE {{url2}}/api/services/2

#############
POST {{url2}}/api/messages
Content-Type: application/json

{
    "data":{
        "phone":"09123456789",
        "content":"111",
        "service":"peman",
        "timestamp":"1640852020",
        "checksum":"aa39a596c2ecc6be790cfda0549c416cd3bd983165df9ed2323ea99433860e39"
    }
}

#############
GET {{url2}}/api/messages
Content-Type: application/json
#############
GET {{url2}}/api/messages?filters[service][name][$eq]=peman&checksum=45e56e7c8b9c71ae531e90ca74d5fc898740ce65bca034f5dd5832e62fd8049e4&timestamp=1640661128&pagination[page]=1&pagination[pageSize]=5&filters[createdAt][$gt]=2021-12-30T08:14:29.565Z
Content-Type: application/json