#############
# @url2=http://localhost:1337
# @url2=https://messagetest.caprover.credot-web.com
@url2=https://message.production.credot-web.com
#############
GET {{url2}}/api/services

#############
POST {{url2}}/api/services
Content-Type: application/json

{
    "data":{
        "name":"test",
        "secret":"123456"
    }
}

#############
DELETE {{url2}}/api/services/2

#############
POST {{url2}}/api/messages
Content-Type: application/json

{
    "data":{
        "phone":"0921771865",
        "content":"test message",
        "service":"peman",
        "timestamp":"1640858017",
        "checksum":"b8796af0a8b9c074aa5dfeab273148bc3b9af4dbb21597203d75103865481a35"
    }
}

#############
GET {{url2}}/api/messages
Content-Type: application/json
#############
GET {{url2}}/api/messages?filters[service][$eq]=peman&checksum=45e56e7c8b9c71e531e90ca74d5fc898740ce65bca034f5dd5832e62fd8049e4&timestamp=1640661128&pagination[page]=1&pagination[pageSize]=5&filters[createdAt][$gt]=2021-12-30T08:14:29.565Z
Content-Type: application/json